// frontend/jobplatform/src/components/common/BasePagination.vue
<template>
    <ul class="pagination float-end">
      <li class="page-item" v-for="page in totalPages" :key="page" :class="{ active: page === currentPage }">
        <a class="page-link" href="#" @click.prevent="goToPage(page)">{{ page }}</a>
      </li>
    </ul>
  </template>
  
  <script>
  
  /* eslint-disable */
  export default {
    props: {
      currentPage: {
        type: Number,
        required: true
      },
      totalPages: {
        type: Number,
        required: true
      },
      goToPage: {
        type: Function,
        required: true
      }
    },
    methods: {
      goToPage(page) {
        this.$emit('goToPage', page);
      }
    }
  };
  </script>
  
  <style scoped>

   
  </style>

// frontend/react_js/src/common/BasePagination.js
import React from 'react';
import PropTypes from 'prop-types';

const Pagination = ({ currentPage, totalPages, onGoToPage  }) => {

  const handlePageChange = (page) => {
    onGoToPage (page);
  };

  return (
    <ul className="pagination float-end">
      {Array.from({ length: totalPages }, (_, index) => index + 1).map(page => (
        <li
          key={page}
          className={`page-item ${page === currentPage ? 'active' : ''}`}
        >
          <a
            className="page-link"
            href="#"
            onClick={(e) => {
              e.preventDefault();
              handlePageChange(page);
            }}
          >
            {page}
          </a>
        </li>
      ))}
    </ul>
  );
};

Pagination.propTypes = {
  currentPage: PropTypes.number.isRequired,
  totalPages: PropTypes.number.isRequired,
  onGoToPage : PropTypes.func.isRequired
};

export default Pagination;
