// frontend/src/components/common/BasePagination.vue
<template>
    <ul class="pagination float-end">
      <li class="page-item" v-for="page in totalPages" :key="page" :class="{ active: page === currentPage }"> 
        <!--totlaPages 만큼의 페이지 번호를 반복하고 각 페이지 번호를 클릭할때 goToPage 함수 호출
        현재 페이지인 경우에는 active클래스를 부여해 현재 페이지임을 표시-->
        <a class="page-link" href="#" @click="goToPage(page)">{{ page }}</a>
      </li>
    </ul>
  </template>
  
  <script>
  
  export default {
    props: {
      currentPage: Number, //현재 페이지 번호
      totalPages: Number, //전체 페이지 수
      goToPage: Function //페이지 이동 함수
    }
  };
  </script>
  
  <style scoped>
  
  </style>

// frontend/react_js/src/common/BasePagination.js
import React from 'react';
import PropTypes from 'prop-types';

const Pagination = ({ currentPage, totalPages, onGoToPage  }) => {

  const handlePageChange = (page) => {
    onGoToPage (page);
  };

  return (
    <ul className="pagination float-end">
      {Array.from({ length: totalPages }, (_, index) => index + 1).map(page => (
        <li
          key={page}
          className={`page-item ${page === currentPage ? 'active' : ''}`}
        >
          <a
            className="page-link"
            href="#"
            onClick={(e) => {
              e.preventDefault();
              handlePageChange(page);
            }}
          >
            {page}
          </a>
        </li>
      ))}
    </ul>
  );
};

Pagination.propTypes = {
  currentPage: PropTypes.number.isRequired,
  totalPages: PropTypes.number.isRequired,
  onGoToPage : PropTypes.func.isRequired
};

export default Pagination;
