// frontend/jobplatform/src/components/enterprise/common/PaginationData.vue
<template>
  <div class="col-lg-4">
    <ul class="pagination">
      <li class="page-item" v-if="props.paginationData.pageGroupsOfCurrentPage > 1">
        <a href="#" class="page-link" :value="props.paginationData.startNumOfPageGroups - 1">
          <i class="fas fa-angle-left"></i>
        </a>
      </li>

      <li
        class="page-item"
        v-for="(page, index) in props.paginationData.endNumOfPageGroups"
        :key="props.paginationData.startNumOfPageGroups + index"
        :value="props.paginationData.startNumOfPageGroups + index"
      >
        <a href="#" class="page-link">{{ props.paginationData.startNumOfPageGroups + index }}</a>
      </li>
      <!-- 온클릭시 페이지 이동 이벤트 일반화 방법이 있을듯??? 찾아보고 하기-->
      <li class="page-item" v-if="props.paginationData.pageGroupsOfCurrentPage < props.paginationData.totalPageGroupsCount">
        <a href="#" class="page-link" :value="props.paginationData.endNumOfPageGroups + 1">
          <i class="fas fa-angle-right"></i>
        </a>
      </li>
    </ul>
  </div>
</template>

<script setup>
import { defineProps } from "vue";

const props = defineProps(["paginationData"]);

console.log("음?");
console.log(props.paginationData.endNumOfPageGroups);
console.log(props.paginationData.endNumOfPageGroups - props.paginationData.showPageGroupsCount * (props.paginationData.pageGroupsOfCurrentPage - 1));
</script>

<style scoped></style>

// frontend/react_js/src/common/PaginationData.js
import React from 'react';
import PropTypes from 'prop-types';

const PaginationData = ({ paginationData, changePageNo }) => {
  const handlePageChange = (newPage) => {
    if (typeof changePageNo === 'function') {
      changePageNo(newPage);
    } else {
      console.error('changePageNo prop is not a function');
    }
  };

  return (
    <div className="col-lg-4">
      <ul className="pagination justify-content-center">
        {/* Previous Page Button */}
        {paginationData.startNumOfPageGroups > paginationData.showPageGroupsCount && (
          <li className="page-item"
              onClick={() => handlePageChange(paginationData.endNumOfPageGroups - paginationData.showPageGroupsCount)}>
            <a href="#" className="page-link">
              <i className="fas fa-angle-left"></i>
            </a>
          </li>
        )}

        {/* Page Numbers */}
        {Array.from({ length: paginationData.showPageGroupsCount }, (_, index) => (
          <li
            className={`page-item ${paginationData.startNumOfPageGroups + index === paginationData.pageGroupsOfCurrentPage ? 'active' : ''}`}
            key={paginationData.startNumOfPageGroups + index}
            onClick={() => handlePageChange(paginationData.startNumOfPageGroups + index)}>
            <a href="#" className="page-link">{paginationData.startNumOfPageGroups + index}</a>
          </li>
        ))}

        {/* Next Page Button */}
        {paginationData.endNumOfPageGroups < paginationData.totalPageGroupsCount && (
          <li className="page-item"
              onClick={() => handlePageChange(paginationData.startNumOfPageGroups + paginationData.showPageGroupsCount)}>
            <a href="#" className="page-link">
              <i className="fas fa-angle-right"></i>
            </a>
          </li>
        )}
      </ul>
    </div>
  );
};

PaginationData.propTypes = {
  paginationData: PropTypes.shape({
    startNumOfPageGroups: PropTypes.number.isRequired,
    endNumOfPageGroups: PropTypes.number.isRequired,
    showPageGroupsCount: PropTypes.number.isRequired,
    pageGroupsOfCurrentPage: PropTypes.number.isRequired,
    totalPageGroupsCount: PropTypes.number.isRequired,
  }).isRequired,
  changePageNo: PropTypes.func.isRequired,
};

export default PaginationData;
