// frontend/react_js/src/enterprise/EnterInfoUpdate.js
import React, { useState } from "react";
import "./EnterInfoUpdate.css";

const EnterInfoUpdate = () => {
    const [entrprsId, setEntrprsId] = useState(''); // 기업아이디
    const [entrprsName, setEntrprsName] = useState(''); // 기업명
    const [zonecode, setZonecode] = useState(''); // 우편번호
    const [entrprsAdrs, setEntrprsAdrs] = useState(''); // 상세주소
    const [entrprsHp, setEntrprsHp] = useState(''); // 기업홈페이지
    const [entrprsPicName, setEntrprsPicName] = useState(''); // 담당자 이름
    const [entrprsPicEml, setEntrprsPicEml] = useState(''); // 담당자 이메일주소
    const [entrprsPicMp, setEntrprsPicMp] = useState(''); // 담당자 전화번호
    const [imgUrl, setImgUrl] = useState(''); // 이미지 임시 URL 저장
    const [img, setImg] = useState(0);
    const [file, setFile] = useState(null);
    const [errorEntrprsPicMp, setErrorEntrprsPicMp] = useState('');

    // useEffect(() => {
    //   const fetchData = async () => {
    //     try {
    //       const res = await axios.get('http://localhost:80/enter/getEnterInfo', {
    //         params: { entrprsSq: entrprsSq }
    //       });
    //       setEntrprsSq(res.data.entrprs_sq);
    //       setEntrprsId(res.data.entrprs_id);
    //       setEntrprsName(res.data.entrprs_name);
    //       setEntrprsAdrs(res.data.entrprs_adrs);
    //       setEntrprsHp(res.data.entrprs_hp);
    //       setEntrprsPicName(res.data.entrprs_pic_name);
    //       setEntrprsPicEml(res.data.entrprs_pic_eml);
    //       setEntrprsPicMp(res.data.entrprs_pic_mp);
    //       setZonecode(res.data.entrprs_zip_code);
    //     } catch (error) {
    //       console.error(error);
    //     }
    //   };
    //   fetchData();
    // }, [entrprsSq]);

    const openPostcode = () => {
        // Daum 주소검색 API를 사용하는 실제 코드
        // new window.daum.Postcode({
        //   oncomplete: (data) => {
        //     setZonecode(data.zonecode);
        //     setEntrprsAdrs(data.roadAddress);
        //   }
        // }).open();
    };

    const handleSubmit = async () => {
        if (!entrprsId || !entrprsName || !entrprsPicName || !entrprsPicMp || !entrprsPicEml) {
            alert('필수 항목을 모두 입력해 주세요.');
            return;
        }

        if (!/^01([0|1|6|7|8|9]?)?([0-9]{3,4})?([0-9]{4})$/.test(entrprsPicMp)) {
            setErrorEntrprsPicMp("휴대폰 번호 형식이 올바르지 않습니다. (-를 제외한 10자리 또는 11자리 숫자)");
            return alert(errorEntrprsPicMp);
        }

        try {
            const data = {
                entrprsId,
                entrprsName,
                entrprsAdrs,
                entrprsHp,
                entrprsPicName,
                entrprsPicEml,
                entrprsPicMp,
                entrprsZoneCode: zonecode
            };

            // Replace with actual API call
            // const res = await axios.post('http://localhost:80/enter/updateEnterInfo', data);
            // if (res.data === '수정완료') {
            //   alert('수정완료 되었습니다.');
            // } else {
            //   alert('수정 실패');
            // }
        } catch (error) {
            console.error(error);
        }
    };

    const uploadImg = (e) => {
        const selectedFile = e.target.files[0];
        if (selectedFile) {
            const url = URL.createObjectURL(selectedFile);
            setImgUrl(url);
            setImg(1);
            setFile(selectedFile);
        } else {
            console.error('No file selected');
            setImg(0);
        }
    };

    return (
        <>
            <section className="page-header page-header-modern bg-color-grey page-header-lg">
                <div className="container">
                    <div className="row">
                        <div className="col-md-12 align-self-center p-static order-2 text-center">
                            <h1 className="font-weight-bold text-dark">기업정보 수정</h1>
                        </div>
                    </div>
                </div>
            </section>

            <div className="d-flex justify-content-center mb-4">
                <div className="profile-image-outer-container">
                    <div className="profile-image-inner-container bg-color-primary">
                        <img src="/assets/avatar.jpg" alt="Profile Image" style={{ display: img === 0 ? 'block' : 'none' }} />
                        <img src={imgUrl} alt="Profile Image" style={{ display: img === 1 ? 'block' : 'none' }} />
                        <span className="profile-image-button bg-color-dark">
                            <i className="fas fa-camera text-light"></i>
                        </span>
                    </div>
                    <input type="file" id="file" className="form-control profile-image-input" onChange={uploadImg}
                        accept="image/gif, image/jpeg, image/png" />
                </div>
            </div>

            <div className="form-container">
                <div className="col-lg-11">
                    <form role="form" className="needs-validation" onSubmit={handleSubmit}>
                        <div className="form-group row">
                            <label className="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 required">
                                아이디
                            </label>
                            <div className="col-lg-9">
                                <input className="form-control text-3 h-auto py-2" type="text"
                                    name="entrprsId" value={entrprsId} readOnly />
                            </div>
                        </div>
                        <div className="form-group row">
                            <label className="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 required">
                                기업명
                            </label>
                            <div className="col-lg-9">
                                <input className="form-control text-3 h-auto py-2" type="text"
                                    name="entrprsName" value={entrprsName} onChange={(e) => setEntrprsName(e.target.value)} required />
                            </div>
                        </div>
                        <div className="form-group row">
                            <label className="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2">
                                기업홈페이지
                            </label>
                            <div className="col-lg-9">
                                <input className="form-control text-3 h-auto py-2" type="url"
                                    name="entrprsHp" value={entrprsHp} onChange={(e) => setEntrprsHp(e.target.value)} />
                            </div>
                        </div>
                        <div className="form-group row mb-4">
                            <label className="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 required">기업 주소</label>
                            <div className="col-lg-7">
                                <input className="form-control text-3 h-auto py-2" type="text"
                                    name="entrprsAdrs" value={zonecode} onChange={(e) => setZonecode(e.target.value)} placeholder="우편번호" />
                            </div>
                            <div className="col-lg-2">
                                <input className="btn btn-primary text-3 h-auto py-2"
                                    type="button" name="entrprsId" value="검 색"
                                    onClick={openPostcode} />
                            </div>
                        </div>

                        <div className="form-group row">
                            <label
                                className="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 "></label>
                            <div className="col-lg-9">
                                <input className="form-control text-3 h-auto py-2" type="text" name="entrprsPicName"
                                    placeholder="상세주소" value={entrprsAdrs} onChange={(e) => setEntrprsAdrs(e.target.value)} />
                            </div>
                        </div>

                        <div className="form-group row">
                            <label className="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 required">
                                기업 담당자
                            </label>
                            <div className="col-lg-9">
                                <input className="form-control text-3 h-auto py-2" type="text"
                                    name="entrprsPicName" value={entrprsPicName} onChange={(e) => setEntrprsPicName(e.target.value)} required />
                            </div>
                        </div>
                        <div className="form-group row">
                            <label className="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 required">
                                기업 담당자 전화번호
                            </label>
                            <div className="col-lg-9">
                                <input className="form-control text-3 h-auto py-2" type="text"
                                    name="entrprsPicMp" value={entrprsPicMp} onChange={(e) => setEntrprsPicMp(e.target.value)} required />
                            </div>
                        </div>
                        <div className="form-group row">
                            <label className="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 required">
                                기업 담당자 이메일주소
                            </label>
                            <div className="col-lg-9">
                                <input className="form-control text-3 h-auto py-2" type="text"
                                    name="entrprsPicEml" value={entrprsPicEml} onChange={(e) => setEntrprsPicEml(e.target.value)} required />
                            </div>
                        </div>
                        <div className="form-group row">
                            <div className="form-group col-lg-9"></div>
                            <div className="d-flex justify-content-center">
                                <div className="form-group">
                                    <input
                                        type="button"
                                        value="Cancel"
                                        className="btn btn-danger btn-modern float-end"
                                    />
                                </div>
                                <div className="form-group">
                                    <input
                                        type="submit"
                                        value="Save"
                                        className="btn btn-primary btn-modern float-end"
                                    />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </>
    );
};

export default EnterInfoUpdate;

// frontend/jobplatform/src/views/fo/enterprise/EnterInfoUpdate.vue
<template>
    <section class="page-header page-header-modern bg-color-grey page-header-lg">
        <div class="container">
            <div class="row">
                <div class="col-md-12 align-self-center p-static order-2 text-center">
                    <h1 class="font-weight-bold text-dark">기업정보 수정</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="d-flex justify-content-center mb-4">
        <div class="profile-image-outer-container">
            <div class="profile-image-inner-container bg-color-primary">
                <img src="@/assets/avatar.jpg" alt="Profile Image" v-if="img==0">
                <img :src="imgUrl" alt="Profile Image" v-if="img==1">
                <span class="profile-image-button bg-color-dark">
                    <i class="fas fa-camera text-light"></i>
                </span>
            </div>
            <input type="file" id="file" class="form-control profile-image-input"
                    @change="uploadImg"
                    accept="image/gif, image/jpeg, image/png">
        </div>
    </div>

<div class="form-container">
    <div class="col-lg-11">
        <form role="form" class="needs-validation" @submit.prevent="handleSubmit">
            <div class="form-group row mb-4">
                <label class="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 required">
                    아이디</label>
                <div class="col-lg-7">
                    <input class="form-control text-3 h-auto py-2" type="text" name="entrprsId" v-model="entrprsId" required @input="repetitionCheck = 0">
                </div>
                <!-- <div class="col-lg-7" v-if="repetitionCheck == 1">
                    <input class="form-control text-3 h-auto py-2" type="text" name="entrprsId" :value="entrprsId" readonly>
                </div> -->
                <div class="col-lg-2" v-if="repetitionCheck == 0">
                    <input class="btn btn-danger text-3 h-auto py-2" 
                    type="button" name="entrprsId" value="중복확인"
                    @click="idRepetitionCheck">
                </div>
                <div class="col-lg-2" v-if="repetitionCheck == 1">
                    <input class="btn btn-primary text-3 h-auto py-2" 
                    type="button" name="entrprsId" value="사용가능"
                    readonly>
                </div>

            </div>
            <div class="form-group row">
                <label class="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 required">
                    기업명</label>
                <div class="col-lg-9">
                    <input class="form-control text-3 h-auto py-2" type="text" name="entrprsName" v-model="entrprsName" required>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2">기업홈페이지</label>
                <div class="col-lg-9">
                    <input class="form-control text-3 h-auto py-2" type="url" name="entrprsHp" v-model="entrprsHp">
                </div>
            </div>
            <div class="form-group row">
                <label class="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2">기업 주소</label>
                <div class="col-lg-9">
                    <input class="form-control text-3 h-auto py-2" type="text" name="entrprsAdrs" v-model="entrprsAdrs"
                        placeholder="Street">
                </div>
            </div>
            <div class="form-group row">
                <label
                    class="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 required">기업 담당자</label>
                <div class="col-lg-9">
                    <input class="form-control text-3 h-auto py-2" type="text" name="entrprsPicName" v-model="entrprsPicName" required >
                </div>
            </div>
            <div class="form-group row">
                <label
                    class="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 required">기업 담당자 전화번호</label>
                <div class="col-lg-9">
                    <input class="form-control text-3 h-auto py-2" type="text" name="entrprsPicMp" v-model="entrprsPicMp" required>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-lg-3 col-form-label form-control-label line-height-9 pt-2 text-2 required">기업 담당자 이메일주소
                    </label>
                <div class="col-lg-9">
                    <input class="form-control text-3 h-auto py-2" type="text" name="entrprsPicEml" v-model="entrprsPicEml"
                        required>
                </div>
            </div>
            <div class="form-group row">
                <div class="form-group col-lg-9">
                </div >

                <div class="d-flex justify-content-center">
                    <div class="form-group ">
                        <input type="button" value="cancel" class="btn btn-danger btn-modern float-end"
                        data-loading-text="Loading...">
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-primary btn-modern float-end"
                        data-loading-text="Loading...">
                    </div>
                </div>

            </div>
        </form>
    </div>
</div>
<!-- <div class="form-group">
    <input type="button" value="도로검색" class="btn btn-primary btn-modern float-end"
    @click="openAddress">
</div> -->
   
</template>

<script setup>
import { onMounted , ref } from 'vue';
import axios from 'axios';

const entrprsSq = ref(''); //기업순번
const entrprsId = ref(''); // 기업아이디
const entrprsName = ref(''); // 기업명
const entrprsAdrs = ref(''); // 기업주소
const entrprsHp = ref(''); // 기업홈페이지
const entrprsPicName = ref(''); // 담당자 이름
const entrprsPicEml = ref(''); // 담당자 이메일주소
const entrprsPicMp = ref(''); //담당자 전화번호

const repetitionCheck = ref(0) //아이디 중복체크 여부 0-사용가능 / 1-사용불가능

const imgUrl = ref(''); // 이미지 임시url 저장

const img = ref(0);

const file = ref(''); // 파일저장

const errorEntrprsPicMp = ref(''); // 핸드폰 번호 에러


onMounted(async() => {
    try{
    const res = await axios.get('http://localhost:80/enter/getEnterInfo', {
                params: {
                    entrprsSq : 1
                }
            });
    console.log(res.data);
    entrprsSq.value = res.data.entrprsSq;
    entrprsId.value = res.data.entrprsId;
    entrprsName.value = res.data.entrprsName;
    entrprsAdrs.value = res.data.entrprsAdrs;
    entrprsHp.value = res.data.entrprsHp;
    entrprsPicName.value = res.data.entrprsPicName;
    entrprsPicEml.value = res.data.entrprsPicEml;
    entrprsPicMp.value = res.data.entrprsPicMp;


    }catch(error){
        console.error(error);
    }
});


// Save 버튼
const handleSubmit = async() => {
    if (!entrprsId.value || !entrprsName.value || !entrprsPicName.value || !entrprsPicMp.value || !entrprsPicEml.value) {
    alert('필수 항목을 모두 입력해 주세요.');
    return;
  }

  if(repetitionCheck.value == 0){
    alert('아이디 중복체크 해주세요');
    return;
  }

  if (!/^01([0|1|6|7|8|9]?)?([0-9]{3,4})?([0-9]{4})$/.test(entrprsPicMp.value)) {
    errorEntrprsPicMp.value =
        "휴대폰 번호 형식이 올바르지 않습니다. (-를 제외한 10자리 또는 11자리 숫자)";
                return alert(errorEntrprsPicMp.value);
    }

  try {
    const data = {
      entrprsSq : entrprsSq.value,
      entrprsId: entrprsId.value,
      entrprsName: entrprsName.value,
      entrprsAdrs: entrprsAdrs.value,
      entrprsHp: entrprsHp.value,
      entrprsPicName: entrprsPicName.value,
      entrprsPicEml: entrprsPicEml.value,
      entrprsPicMp: entrprsPicMp.value
    };

    // console test
    console.log(data);

    try{
    const res = await axios.post('http://localhost:80/enter/updateEnterInfo',  data);
            console.log(res.data);
            if(res.data == '수정완료'){
                alert('수정완료 되었습니다.');
            }else{
                alert('수정 실패');
            }

    }catch(error){
        console.error(error);
    } 

  }catch(error){
    console.log(error);
  }
};



const uploadImg = async (e) => {
     file.value = e.target.files[0]; // files 배열에서 첫 번째 파일 선택
    if (file.value) {
        let url = URL.createObjectURL(file.value);
        imgUrl.value = url;
        img.value = 1;
        console.log(imgUrl);
        console.log(imgUrl.value);
        console.log(file);
    } else {
        console.error('No file selected');
        img.value = 0;
    }
};

//아이디 중복확인
// 아이디중복확인
const idRepetitionCheck = async() => {
    console.log("중복확인")
    if(!entrprsId.value){
    alert("아이디를 입력해 주세요");
    return;
    }
      
    try{
    const res = await axios.post('http://localhost:80/enter/idRepetitionCheck', {entrprsId : entrprsId.value});
            console.log(res.data);
            if(res.data == '사용가능'){
                repetitionCheck.value = 1;
            }else{
                alert('중복된 아이디 입니다.')
                repetitionCheck.value = 0;
            }

    }catch(error){
        console.error(error);
    }       
};


// 주소검색 api
// const openAddress = () => {
    
// }

</script>

<style>
.form-container {
    display: flex;
    justify-content: center;
}

</style>
