// frontend/react_js/src/user/JobPostingListView.js
import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';

import"./JobPostingListView.css"
// moment를 사용하기 위해 npm install moment
import moment from 'moment';
import BasePagination from '../common/BasePagination';
// import SearchComponent from './SearchComponent';

/*
JobPostingListView.css 내에 .dropdown 지워야 list div css나옴
수시로 체크 요망 
*/

const JobInfo = () => {
  
  const [items, setItems] = useState([]);
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage] = useState(12);
  const [sortOption, setSortOption] = useState('regstrStrtDtm');

  const [regionSearch, setRegionSearch] = useState('');
  const [jobTypeSearch, setJobTypeSearch] = useState('');

  const [selectedLocations, setSelectedLocations] = useState([]);
  const [selectedCareers, setSelectedCareers] = useState([]);
  const [selectedEducations, setSelectedEducations] = useState([]);
  const [selectedJobTypes, setSelectedJobTypes] = useState([]);

  const [showDropdown, setShowDropdown] = useState({
    region: false,
    career: false,
    education: false,
    jobType: false,
  });

  // Mock data for areas and jobs
  const areas = [
    { id: '1', areaName: '서울' },
    { id: '2', areaName: '부산' },

  ];
  const jobs = [
    { id: '1', jobScName: '개발자' },
    { id: '2', jobScName: '디자이너' },

  ];


  useEffect(() => {
    const fetchItems = async () => {
      try {
        const response = await axios.get('/board/list/jobPosting', {
          params: { sortBy: sortOption }
        });
        setItems(response.data || []);
      } catch (error) {
        console.error('Error fetching items:', error);
      }
    };

    fetchItems();
  }, [sortOption]);

  // 공고리스트 db값 가져오는 로직 
  const getJobList = async () => {
    try{
      const resp = await axios.get('/board/list/jobPosting',{
        params: { sorrtBy: sortOption}
      });
      setItems(resp.data || []);
    } catch (error){
      console.error('Error fetching job list:', error);
    }
    
  };

  useEffect(() => {
    getJobList();
  }, [sortOption]);

  

  const filteredItems = useMemo(() => {
    const today = moment().format('YYYY-MM-DD');
    return items.filter(item => {
      let isValid = true;

      if (selectedLocations.length > 0 && !selectedLocations.some(location => item.workArea.includes(location))) {
        isValid = false;
      }
      if (selectedCareers.length > 0 && !selectedCareers.includes(item.cr)) {
        isValid = false;
      }
      if (selectedEducations.length > 0 && !selectedEducations.includes(item.edctn)) {
        isValid = false;
      }
      if (selectedJobTypes.length > 0 && !selectedJobTypes.some(jobType => item.jobName.includes(jobType))) {
        isValid = false;
      }

      if (moment(item.regstrStrtDtm).isAfter(today)) {
        isValid = false;
      }

      return isValid;
    });
  }, [items, selectedLocations, selectedCareers, selectedEducations, selectedJobTypes]);

  const paginatedItems = useMemo(() => {
    const startIndex = (currentPage - 1) * itemsPerPage;
    const endIndex = startIndex + itemsPerPage;
    return filteredItems.slice(startIndex, endIndex);
  }, [filteredItems, currentPage, itemsPerPage]);

  const totalPages = useMemo(() => Math.ceil(filteredItems.length / itemsPerPage), [filteredItems, itemsPerPage]);

  const handlePageChange = (page) => {
    if (page >= 1 && page <= totalPages) {
      setCurrentPage(page);
    }
  };

  const handleSearchResult = (searchResults) => {
    setItems(searchResults);
    setCurrentPage(1);
  };

  const clearAllFilter = () => {
    setSelectedLocations([]);
    setSelectedCareers([]);
    setSelectedEducations([]);
    setSelectedJobTypes([]);
    // fetchItems();
  };

  const toggleDropdown = (type) => {
    setShowDropdown(prev => ({
      ...prev,
      [type]: !prev[type],
    }));
  };

  const filteredAreas = useMemo(() => {
    return areas.filter(area => area.areaName.toLowerCase().includes(regionSearch.toLowerCase()));
  }, [areas, regionSearch]);

  const filteredJobTypes = useMemo(() => {
    return jobs.filter(job => job.jobScName.toLowerCase().includes(jobTypeSearch.toLowerCase()));
  }, [jobs, jobTypeSearch]);

  const educationMapping = {
    '606': '학력무관',
    '605': '고등학교 이상',
    '604': '대학교(2,3년제) 이상',
    '603': '대학교(4년제) 이상',
    '602': '석사',
    '601': '박사'
  };

  const careerMapping = {
    '801': '경력무관',
    '802': '신입',
    '803': '경력'
  };

  const getEducationText = (value) => educationMapping[value] || value;
  const getCareerText = (value) => careerMapping[value] || value;

  return (
    <div>
      <section className="page-header page-header-modern bg-color-grey page-header-md">
        <div className="container">
          <div className="row">
            <div className="col-md-12 align-self-center p-static order-2 text-center">
              <h1 className="text-dark font-weight-bold text-8">일반게시판</h1>
              <span className="sub-title text-dark">자유로운 글 작성!</span>
            </div>
            <div className="col-md-12 align-self-center order-1">
              <ul className="breadcrumb d-block text-center">
                <li><Link to="/">Home</Link></li>
                <li className="active">일반게시판</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      <section className="card card-admin">
        <div className="container py-4">
          <div className="d-flex justify-content-end">
            {/* 유저는 등록 리스트내에 등록버튼이 필요 없음 공고 확인과 입사지원만 하기 때문 그래서 지움*/}
            {/* <Link to="/board/jobPostingInsert" className="btn btn-primary">등록</Link> */}
          </div>

          <div className="list-container">
            <div className="list-header">
              <div className="search-options">
                <div className="dropdown-wrapper">
                  <button onClick={() => toggleDropdown('region')}>지역</button>
                  {showDropdown.region && (
                    <div className="dropdown">
                      <input
                        type="text"
                        value={regionSearch}
                        onChange={(e) => setRegionSearch(e.target.value)}
                        placeholder="지역 검색"
                      />
                      {filteredAreas.map(area => (
                        <label key={area.id}>
                          <input
                            type="checkbox"
                            checked={selectedLocations.includes(area.areaName)}
                            onChange={(e) => {
                              setSelectedLocations(prev =>
                                e.target.checked
                                  ? [...prev, area.areaName]
                                  : prev.filter(location => location !== area.areaName)
                              );
                            }}
                          /> {area.areaName}
                        </label>
                      ))}
                    </div>
                  )}
                </div>

                <div className="dropdown-wrapper">
                  <button onClick={() => toggleDropdown('career')}>경력</button>
                  {showDropdown.career && (
                    <div className="dropdown">
                      <label>
                        <input
                          type="checkbox"
                          checked={selectedCareers.includes('801')}
                          onChange={(e) => {
                            setSelectedCareers(prev =>
                              e.target.checked
                                ? [...prev, '801']
                                : prev.filter(career => career !== '801')
                            );
                          }}
                        /> 경력무관
                      </label>
                      <label>
                        <input
                          type="checkbox"
                          checked={selectedCareers.includes('802')}
                          onChange={(e) => {
                            setSelectedCareers(prev =>
                              e.target.checked
                                ? [...prev, '802']
                                : prev.filter(career => career !== '802')
                            );
                          }}
                        /> 신입
                      </label>
                      <label>
                        <input
                          type="checkbox"
                          checked={selectedCareers.includes('803')}
                          onChange={(e) => {
                            setSelectedCareers(prev =>
                              e.target.checked
                                ? [...prev, '803']
                                : prev.filter(career => career !== '803')
                            );
                          }}
                        /> 경력
                      </label>
                    </div>
                  )}
                </div>

                <div className="dropdown-wrapper">
                  <button onClick={() => toggleDropdown('education')}>학력</button>
                  {showDropdown.education && (
                    <div className="dropdown">
                      <label>
                        <input
                          type="checkbox"
                          checked={selectedEducations.includes('606')}
                          onChange={(e) => {
                            setSelectedEducations(prev =>
                              e.target.checked
                                ? [...prev, '606']
                                : prev.filter(education => education !== '606')
                            );
                          }}
                        /> 학력무관
                      </label>
                      <label>
                        <input
                          type="checkbox"
                          checked={selectedEducations.includes('605')}
                          onChange={(e) => {
                            setSelectedEducations(prev =>
                              e.target.checked
                                ? [...prev, '605']
                                : prev.filter(education => education !== '605')
                            );
                          }}
                        /> 고등학교 이상
                      </label>
                      <label>
                        <input
                          type="checkbox"
                          checked={selectedEducations.includes('604')}
                          onChange={(e) => {
                            setSelectedEducations(prev =>
                              e.target.checked
                                ? [...prev, '604']
                                : prev.filter(education => education !== '604')
                            );
                          }}
                        /> 대학교(2,3년제) 이상
                      </label>
                      <label>
                        <input
                          type="checkbox"
                          checked={selectedEducations.includes('603')}
                          onChange={(e) => {
                            setSelectedEducations(prev =>
                              e.target.checked
                                ? [...prev, '603']
                                : prev.filter(education => education !== '603')
                            );
                          }}
                        /> 대학교(4년제) 이상
                      </label>
                      <label>
                        <input
                          type="checkbox"
                          checked={selectedEducations.includes('602')}
                          onChange={(e) => {
                            setSelectedEducations(prev =>
                              e.target.checked
                                ? [...prev, '602']
                                : prev.filter(education => education !== '602')
                            );
                          }}
                        /> 석사
                      </label>
                      <label>
                        <input
                          type="checkbox"
                          checked={selectedEducations.includes('601')}
                          onChange={(e) => {
                            setSelectedEducations(prev =>
                              e.target.checked
                                ? [...prev, '601']
                                : prev.filter(education => education !== '601')
                            );
                          }}
                        /> 박사
                      </label>
                    </div>
                  )}
                </div>

                <div className="dropdown-wrapper">
                  <button onClick={() => toggleDropdown('jobType')}>직종</button>
                  {showDropdown.jobType && (
                    <div className="dropdown">
                      <input
                        type="text"
                        value={jobTypeSearch}
                        onChange={(e) => setJobTypeSearch(e.target.value)}
                        placeholder="직종 검색"
                      />
                      {filteredJobTypes.map(job => (
                        <label key={job.id}>
                          <input
                            type="checkbox"
                            checked={selectedJobTypes.includes(job.jobScName)}
                            onChange={(e) => {
                              setSelectedJobTypes(prev =>
                                e.target.checked
                                  ? [...prev, job.jobScName]
                                  : prev.filter(jobType => jobType !== job.jobScName)
                              );
                            }}
                          /> {job.jobScName}
                        </label>
                      ))}
                    </div>
                  )}
                </div>
              </div>
              {/* <SearchComponent onSearchResult={handleSearchResult} /> */}
              <div>
                <select value={sortOption} onChange={(e) => setSortOption(e.target.value)}>
                  <option value="regstrStrtDtm">최신순</option>
                  <option value="apply">지원자순</option>
                  <option value="hits">조회수순</option>
                </select>
                {/* //디비 값 받는거 연습중------------------ */}
                {/* <ul>  
                    {jobList.map((joblist) => (
                      // 4) map 함수로 데이터 출력
                      <li key={joblist.jbpSq}>
                        <Link to={`/board/${jobList.jbpSq}`}>{joblist.edctn}</Link>
                      </li>
                    ))}
                </ul> */}

                <button onClick={clearAllFilter} className="btn btn-primary">초기화</button>
              </div>
            </div>
            <div className="list-body">
              {paginatedItems.length > 0 ? (
                paginatedItems.map((item, idx) => (
                  <div key={idx} className="custom">
                    <div>
                      <Link to={`/board/detail/jobPosting/${item.jbpSq}`}>{item.jbpTl}</Link>
                    </div>
                    <div>{getEducationText(item.edctn)}</div>
                    <div>{getCareerText(item.cr)}</div>
                    <div>{item.jobName}</div>
                    <div>{item.workArea}</div>

                    
                  </div>
                ))
              ) : (
                <div className="text-center py-5">
                  <p className="text-muted">결과가 없습니다.</p>
                </div>
              )}
            </div>
          </div>
          <div className="pagenation-wrapper">
            <BasePagination
              currentPage={currentPage}
              totalPages={totalPages}
              onGoToPage={handlePageChange}
            />
          </div>
        </div>
      </section>
    </div>
  );
};

export default JobInfo;

// frontend/jobplatform/src/views/fo/enterprise/JobPostingListView.vue
<template>
  <div>
    <section class="page-header page-header-modern bg-color-grey page-header-md">
      <div class="container">
        <div class="row">
          <div class="col-md-12 align-self-center p-static order-2 text-center">
            <h1 class="text-dark font-weight-bold text-8">일반게시판</h1>
            <span class="sub-title text-dark">자유로운 글 작성!</span>
          </div>
          <div class="col-md-12 align-self-center order-1">
            <ul class="breadcrumb d-block text-center">
              <li><a href="/">Home</a></li>
              <li class="active">일반게시판</li>
            </ul>
          </div>
        </div>
      </div>
    </section>

    <section class="card card-admin">
      <div class="container py-4">
        <div class="d-flex justify-content-end">
          <router-link to="/board/jobPostingInsert" class="btn btn-primary">등록</router-link>
        </div>

        <!-- 검색 옵션 UI -->

        <!-- 게시글 목록 -->
        <div class="list-container">
          <div class="list-header">
            <div class="search-options">
              <div class="dropdown-wrapper">
                <button @click="toggleDropdown('region')">지역</button>
                <div v-if="showDropdown.region" class="dropdown">
                  <!-- 검색창 -->
                  <input type="text" v-model="regionSearch" placeholder="지역 검색">
                  <!-- 지역 목록 -->
                  <label v-for="area in filteredAreas" :key="area.id">
                    <input type="checkbox" v-model="selectedLocations" :value="area.areaName"> {{ area.areaName }}
                  </label>
                </div>
              </div>

              <div class="dropdown-wrapper">
                <button @click="toggleDropdown('career')">경력</button>
                <div v-if="showDropdown.career" class="dropdown">
                  <label><input type="checkbox" v-model="selectedCareers" value="801"> 경력무관</label>
                  <label><input type="checkbox" v-model="selectedCareers" value="802"> 신입</label>
                  <label><input type="checkbox" v-model="selectedCareers" value="803"> 경력</label>
                </div>
              </div>

              <div class="dropdown-wrapper">
                <button @click="toggleDropdown('education')">학력</button>
                <div v-if="showDropdown.education" class="dropdown">
                  <label><input type="checkbox" v-model="selectedEducations" value="606"> 학력무관</label>
                  <label><input type="checkbox" v-model="selectedEducations" value="605"> 고등학교 이상</label>
                  <label><input type="checkbox" v-model="selectedEducations" value="604"> 대학교(2,3년제) 이상</label>
                  <label><input type="checkbox" v-model="selectedEducations" value="603"> 대학교(4년제) 이상</label>
                  <label><input type="checkbox" v-model="selectedEducations" value="602"> 석사</label>
                  <label><input type="checkbox" v-model="selectedEducations" value="601"> 박사</label>
                </div>
              </div>

              <div class="dropdown-wrapper">
                <button @click="toggleDropdown('jobType')">직종</button>
                <div v-if="showDropdown.jobType" class="dropdown">
                  <!-- 검색창 -->
                  <input type="text" v-model="jobTypeSearch" placeholder="직종 검색">
                  <!-- 직종 목록 -->
                  <label v-for="job in filteredJobTypes" :key="job.id">
                    <input type="checkbox" v-model="selectedJobTypes" :value="job.jobScName"> {{ job.jobScName }}
                  </label>
                </div>
              </div>
            </div>
            <SearchComponent @searchResult="handleSearchResult" />
            <div>
              <select v-model="sortOption" @change="fetchSortedItems">
                <option value="regstrStrtDtm">최신순</option>
                <option value="apply">지원자순</option>
                <option value="hits">조회수순</option>
              </select>
              <button @click="clearAllFilter" class="btn btn-primary">초기화</button>
            </div>
          </div>
          <div class="list-body">
            <div v-if="paginatedItems.length > 0">
              <div v-for="(item, idx) in paginatedItems" :key="idx" class="custom">
                <div><router-link :to="`/board/detail/jobPosting/${item.jbpSq}`">{{ item.jbpTl }}</router-link></div>
                <div>{{ getEducationText(item.edctn) }}</div>
                <div>{{ getCareerText(item.cr) }}</div>
                <div>{{ formatJobName(item.jobName) }}</div>
                <div>{{ formatWorkArea(item.workArea) }}</div>
              </div>
            </div>
            <!-- 검색 결과가 없을 때 표시될 메시지 -->
            <div v-else class="text-center py-5">
              <p class="text-muted">결과가 없습니다.</p>
            </div>
          </div>
        </div>
        <div class="pagenation-wrapper">
          <BasePagination :currentPage="state.currentPage" :totalPages="totalPages" @goToPage="goToPage" />
        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
import { ref, reactive, computed, watch, onMounted } from 'vue';
import { api } from '@/axios.js';
import BasePagination from "@/components/common/BasePagination.vue";
import SearchComponent from '@/components/fo/enterprise/SearchComponent.vue';
import moment from 'moment';

const state = reactive({
  items: [],
  currentPage: 1,
  itemsPerPage: 12
});

const sortOption = ref('regstrStrtDtm');

// 초기 데이터 로드
const fetchItems = async () => {
  try {
    const response = await api.$get('/board/list/jobPosting', {
      params: { sortBy: sortOption.value }
    });
    state.items = response;
  } catch (error) {
    console.error('Error fetching items:', error);
  }
};

const formatJobName = (jobName) => {
  if (typeof jobName === 'string') {
    // 문자열에서 대괄호와 따옴표 제거
    let cleaned = jobName.replace(/^\[|\]$/g, '').replace(/"/g, '');
    // 쉼표로 분리된 항목들을 배열로 만들고 다시 조인
    return cleaned.split(',').map(item => item.trim()).join(', ');
  } else if (Array.isArray(jobName)) {
    // 이미 배열인 경우 직접 조인
    return jobName.join(', ');
  }
  // 그 외의 경우 원래 값 반환
  return jobName;
};

const formatWorkArea = (workArea) => {
  if (typeof workArea === 'string') {
    // 문자열에서 대괄호와 따옴표 제거
    let cleaned = workArea.replace(/^\[|\]$/g, '').replace(/"/g, '');
    // 쉼표로 분리된 항목들을 배열로 만들고 다시 조인
    return cleaned.split(',').map(item => item.trim()).join(', ');
  } else if (Array.isArray(workArea)) {
    // 이미 배열인 경우 직접 조인
    return workArea.join(', ');
  }
  // 그 외의 경우 원래 값 반환
  return workArea;
};

// 컴포넌트가 마운트된 후 데이터 로드
onMounted(() => {
  fetchItems();
});

const fetchSortedItems = () => {
  state.currentPage = 1; // 페이지를 첫 페이지로 초기화
  fetchItems();
};

// 페이지네이션 계산
const paginatedItems = computed(() => {
  const startIndex = (state.currentPage - 1) * state.itemsPerPage;
  const endIndex = startIndex + state.itemsPerPage;
  return filteredItems.value.slice(startIndex, endIndex);
});

// 전체 페이지 수 계산
const totalPages = computed(() => Math.ceil(filteredItems.value.length / state.itemsPerPage));

// 지역, 직업목록
const areas = ref([]);
const jobs = ref([]);

const fetchAreas = async () => {
  try {
    const response = await api.$get(`/areas`);
    areas.value = response;
  } catch (error) {
    console.error('Error fetching areas:', error);
  }
};

const fetchJobs = async () => {
  try {
    const response = await api.$get(`/jobs`);
    jobs.value = response;
  } catch (error) {
    console.error('Error fetching jobs:', error);
  }
};

onMounted(() => {
  fetchAreas();
  fetchJobs();
});

// 선택된 옵션들
const selectedLocations = ref([]);
const selectedCareers = ref([]);
const selectedEducations = ref([]);
const selectedJobTypes = ref([]);

// 선택값 초기화 

const clearAll= ()=>{
  selectedCareers.value = [];
  selectedEducations.value = [];
  selectedJobTypes.value = [];
  selectedLocations.value = [];
}

// 선택된 값, 검색 값 초기화
const clearAllFilter =()=>{
  clearAll();
  fetchItems();
}

// 드롭다운 메뉴 표시 상태
const showDropdown = reactive({
  region: false,
  career: false,
  education: false,
  jobType: false
});

// 필터된 아이템들 계산
const filteredItems = computed(() => {
  if (!state.items) return [];
  const today = moment().format('YYYY-MM-DD');
  return state.items.filter(item => {
    let isValid = true;

    if (selectedLocations.value.length > 0 && !selectedLocations.value.some(location => item.workArea.includes(location))) {
      isValid = false;
    }
    if (selectedCareers.value.length > 0 && !selectedCareers.value.includes(item.cr)) {
      isValid = false;
    }
    if (selectedEducations.value.length > 0 && !selectedEducations.value.includes(item.edctn)) {
      isValid = false;
    }
    if (selectedJobTypes.value.length > 0 && !selectedJobTypes.value.some(jobType => item.jobName.includes(jobType))) {
      isValid = false;
    }

    // 공고 시작일이 오늘 날짜보다 작은지 확인
    if (moment(item.regstrStrtDtm).isAfter(today)) {
      isValid = false;
    }

    return isValid;
  });
});

// 페이지 변경 함수
function goToPage(page) {
  if (page >= 1 && page <= totalPages.value) {
    state.currentPage = page;
  }
}

// Watchers
watch(selectedLocations, () => {
  state.currentPage = 1;
});
watch(selectedCareers, () => {
  state.currentPage = 1;
});
watch(selectedEducations, () => {
  state.currentPage = 1;
});
watch(selectedJobTypes, () => {
  state.currentPage = 1;
});

watch(sortOption, fetchSortedItems);

// 검색 결과 처리 함수
const handleSearchResult = (searchResults) => {
  state.items = searchResults;
  state.currentPage = 1;
}

// 드롭다운 토글 함수
function toggleDropdown(type) {
  for (const key in showDropdown) {
    if (key === type) {
      showDropdown[key] = !showDropdown[key];
    } else {
      showDropdown[key] = false;
    }
  }
}

const regionSearch = ref('');
const jobTypeSearch = ref('');

// 필터링된 지역 목록 계산
const filteredAreas = computed(() => {
  return areas.value.filter(area => {
    return area.areaName.toLowerCase().includes(regionSearch.value.toLowerCase());
  });
});

// 필터링된 직종 목록 계산
const filteredJobTypes = computed(() => {
  return jobs.value.filter(job => {
    return job.jobScName.toLowerCase().includes(jobTypeSearch.value.toLowerCase());
  });
});

// 학력 매핑 테이블
const educationMapping = {
  '606': '학력무관',
  '605': '고등학교 이상',
  '604': '대학교(2,3년제) 이상',
  '603': '대학교(4년제) 이상',
  '602': '석사',
  '601': '박사'
};

// 경력 매핑 테이블
const careerMapping = {
  '801': '경력무관',
  '802': '신입',
  '803': '경력'
};

// 학력 텍스트 반환 함수
const getEducationText = (value) => {
  return educationMapping[value] || value;
};

// 경력 텍스트 반환 함수
const getCareerText = (value) => {
  return careerMapping[value] || value;
};
</script>

<style scoped>
.list-container {
  margin-bottom: 60px; /* 페이지네이션 영역과의 여백을 추가합니다 */
  position: relative; /* 페이지네이션을 포함하는 부모 요소에 상대적인 위치를 설정합니다 */
}
.list-header {
  display: flex;
}
.list-header > div {
  margin-left: 50px;
}
.list-body {
  margin-top: 50px;
}
.custom {
  background-color: #ffffff;
  border-radius: 0.5rem;
  padding: 1rem;
  margin: 15px;
  width: calc(25% - 30px); /* 4개의 아이템이 한 줄에 나타나도록 설정 */
  border: 1px solid #002C7B;
  text-align: center;
  float: left;
  height: 150px;
  overflow: hidden;
}
.row {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
}

.search-options {
  margin-top: 20px;
  display: flex;
  align-items: center;
}

.dropdown-wrapper {
  position: relative; /* 부모 요소에 대해 위치를 상대적으로 설정 */
}

.search-options button {
  padding: 8px 16px;
  font-size: 16px;
  background-color: #3498db;
  color: white;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  margin-right: 10px;
}

.search-options button:hover {
  background-color: #2980b9;
}

.dropdown {
  position: absolute;
  top: 100%; /* 버튼 바로 아래에 위치하도록 설정 */
  left: 0;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
  margin-top: 5px;
  max-height: 200px; /* 드롭다운의 최대 높이 설정 */
  overflow-y: auto; /* 세로 스크롤 처리 */
  
}

.dropdown label {
  display: block;
  padding: 10px;
  
}

.dropdown label:hover {
  background-color: #f1f1f1;
}

.pagenation-wrapper{
  position: absolute; /* 절대적인 위치에서 설정합니다 */
  width: 100%;
  z-index: 1000;
  bottom: -50px; /* 페이지네이션을 게시물 아래로 이동시킵니다 */

}
.container{
  position : relative;
  margin-bottom: 50px;
}
</style>
