// frontend/jobplatform/src/components/fo/user/mypage/MypageProposedPositionList.vue
<template>
    <div v-if="result">
        <div class="row">
            <div style="display: flex; justify-content: right;">
                <input type="text" maxlength="80" class="form-control text-1" placeholder="검색어 입력" style="width: 140px;" />
                <span class="center" style="margin-left: 10px">
                    <i class="fas fa-search" style="width: max-content; font-size: 20px"></i>
                </span>
            </div>
        </div>
        <div class="row" style="margin-top: 20px;">
            <!-- 리스트 -->
            <div v-for="(post, i) in result" :key="i" style="border-bottom: 1px solid #eae; margin-bottom: 16px;">
                <table class="table table-bordered" style="margin-bottom: 10; table-layout: fixed; width: 100%;">
                    <thead>
                        <tr>
                            <th colspan="2" style="font-size: large;">
                                {{ post.entrprs_name }}
                            </th>
                            <th colspan="3">
                                {{ post.jbp_tl }}
                            </th>
                            <th colspan="1" style="text-align: center;">
                                조회수&nbsp;&nbsp;{{ post.hits }}
                            </th>
                        </tr>
                    </thead>
                    <tbody style="text-align: center;">
                        <tr style="vertical-align: middle;">
                            <th>
                                급여&nbsp;&nbsp;{{ post.slry }}
                            </th>
                            <th>
                                {{ post.edctn }}
                            </th>
                            <th>
                                {{ post.cr }}
                            </th>
                            <th>
                                {{ post.work_form }}
                            </th>
                            <th style="line-height: 1.2em;">
                                제안일<br/>{{formatDateYMD(post.prpsl_dtm)}}
                            </th>
                            <th style="line-height: 1.2em;">
                                마감일<br/>{{formatDateYMD(post.regstr_dln_dtm)}}
                            </th>
                        </tr>
                        <tr>
                            <th>근무지역</th>
                            <th colspan="2" style="text-align: left; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                                <template v-if="!post.areas">해당사항없음</template>
                                <template v-for="(area, i) in post.areas" :key="i">
                                    {{ area }}<span v-if="i < post.areas.length - 1">, </span>
                                </template>
                            </th>
                            <th>직종</th>
                            <th colspan="2" style="text-align: left; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                                <template v-if="!post.jobs">해당사항없음</template>
                                <template v-for="(job, i) in post.jobs" :key="i">
                                    {{ job }}<span v-if="i < post.jobs.length - 1">, </span>
                                </template>
                            </th>
                        </tr>
                        <tr>
                            <th>필요스킬</th>
                            <th colspan="4" style="text-align: left; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                                <template v-if="!post.skills">해당사항없음</template>
                                <template v-for="(skill, i) in post.skills" :key="i">
                                    {{ skill }}<span v-if="i < post.skills.length - 1">,&nbsp;&nbsp;</span>
                                </template>
                            </th>
                            <th>
                                <a href="#" class="btn btn-outline btn-primary" style="padding: 4px 8px;">수 락</a>
                                <a href="#" class="btn btn-outline btn-secondary" style="padding: 4px 8px; margin-left: 10px;">거 절</a>
                            </th>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- 페이지네이션 -->
        <div class="row" style="margin-top: 35px;">
            <div class="col-3"></div>
            <div class="col-6" style="display: flex; justify-content: center;">
                <paginate
                    :page-count="'{{ result.length }}'"
                    :page-range="5"
                    :margin-pages="0"
                    :break-view-class="'dispalyNone pointer'"
                    :page-class="'pointer'"
                    :prev-class="'pointer'"
                    :next-class="'pointer'"
                    :click-handler="'functionName'"
                    :prev-text="'<<'"
                    :next-text="'>>'"
                >
                </paginate>
            </div>
            <div class="col-3"></div>
        </div>
    </div>
</template>

<script setup>
    import { ref, onMounted } from 'vue'
    import Paginate from 'vuejs-paginate-next';
    import { api } from '@/axios';
    import { formatDateYMD } from '@/tools';

    let result = ref(null);

    onMounted(async() => {
        result.value = await api.$get("user/mypage/ppJobPost", {
            params: {
                mbr_sq : 1
            }
        });
    });

</script>

<style>
    .dispalyNone {
        display: none;
    }
    .pointer {
        cursor: pointer;
    }
    .center {
        display: flex;
        align-items: center;
        justify-content: center;
    }
    
</style>

// frontend/react_js/src/mypage/MypageProposedPositionList.js
import React from 'react';
import './MypageProposedPositionList.css';
// import { formatDateYMD } from '@/tools';
// import Paginate from 'react-paginate';

const PositionProposalList = () => {
  // 데이터 주석 처리, 필요한 상태만 유지
  const result = {
    totalPostsCount: 1,
    jobPosts: [
      {
        entrprs_name: 'Enterprise 1',
        jbp_tl: 'Job Title 1',
        hits: 123,
        slry: '50,000',
        edctn: 'Bachelor',
        cr: '3 years',
        work_form: 'Full-time',
        prpsl_dtm: '2023-07-21',
        regstr_dln_dtm: '2023-08-21',
        areas: ['Seoul', 'Busan'],
        jobs: ['Developer', 'Manager'],
        skills: ['JavaScript', 'React'],
      },
    ],
  };

  // Pagination handler
  const handlePageClick = (data) => {
    console.log(`Selected page: ${data.selected + 1}`);
  };

  return (
    <div>
      {result && result.totalPostsCount !== 0 ? (
        <div>
          <div className="row">
            <div style={{ display: 'flex', justifyContent: 'right' }}>
              <input
                type="text"
                maxLength="80"
                className="form-control text-1"
                placeholder="검색어 입력"
                style={{ width: '140px' }}
              />
              <span className="center" style={{ marginLeft: '10px' }}>
                <i className="fas fa-search" style={{ width: 'max-content', fontSize: '20px' }}></i>
              </span>
            </div>
          </div>
          <div className="row" style={{ marginTop: '20px' }}>
            {result.jobPosts.map((post, i) => (
              <div
                key={i}
                style={{ borderBottom: '1px solid #eae', marginBottom: '16px' }}
              >
                <table
                  className="table table-bordered"
                  style={{ marginBottom: 10, tableLayout: 'fixed', width: '100%' }}
                >
                  <thead>
                    <tr>
                      <th colSpan="2" style={{ fontSize: 'large' }}>
                        {post.entrprs_name}
                      </th>
                      <th colSpan="3">{post.jbp_tl}</th>
                      <th colSpan="1" style={{ textAlign: 'center' }}>
                        조회수&nbsp;&nbsp;{post.hits}
                      </th>
                    </tr>
                  </thead>
                  <tbody style={{ textAlign: 'center' }}>
                    <tr style={{ verticalAlign: 'middle' }}>
                      <th>급여&nbsp;&nbsp;{post.slry}</th>
                      <th>{post.edctn}</th>
                      <th>{post.cr}</th>
                      <th>{post.work_form}</th>
                      <th style={{ lineHeight: '1.2em' }}>
                        제안일
                        <br />
                        {/* {formatDateYMD(post.prpsl_dtm)} */}
                      </th>
                      <th style={{ lineHeight: '1.2em' }}>
                        마감일
                        <br />
                        {/* {formatDateYMD(post.regstr_dln_dtm)} */}
                      </th>
                    </tr>
                    <tr>
                      <th>근무지역</th>
                      <th
                        colSpan="2"
                        style={{
                          textAlign: 'left',
                          whiteSpace: 'nowrap',
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                        }}
                      >
                        {post.areas ? (
                          post.areas.map((area, i) => (
                            <React.Fragment key={i}>
                              {area}
                              {i < post.areas.length - 1 && ', '}
                            </React.Fragment>
                          ))
                        ) : (
                          '해당사항없음'
                        )}
                      </th>
                      <th>직종</th>
                      <th
                        colSpan="2"
                        style={{
                          textAlign: 'left',
                          whiteSpace: 'nowrap',
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                        }}
                      >
                        {post.jobs ? (
                          post.jobs.map((job, i) => (
                            <React.Fragment key={i}>
                              {job}
                              {i < post.jobs.length - 1 && ', '}
                            </React.Fragment>
                          ))
                        ) : (
                          '해당사항없음'
                        )}
                      </th>
                    </tr>
                    <tr>
                      <th>필요스킬</th>
                      <th
                        colSpan="4"
                        style={{
                          textAlign: 'left',
                          whiteSpace: 'nowrap',
                          overflow: 'hidden',
                          textOverflow: 'ellipsis',
                        }}
                      >
                        {post.skills ? (
                          post.skills.map((skill, i) => (
                            <React.Fragment key={i}>
                              {skill}
                              {i < post.skills.length - 1 && ', '}
                            </React.Fragment>
                          ))
                        ) : (
                          '해당사항없음'
                        )}
                      </th>
                      <th>
                        <button className="btn btn-outline btn-primary" style={{ padding: '4px 8px' }}>
                          수 락
                        </button>
                        <button
                          className="btn btn-outline btn-secondary"
                          style={{ padding: '4px 8px', marginLeft: '10px' }}
                          // onClick={() => refuseProposedPostion(post.pstn_prpsl_sq)}
                        >
                          거 절
                        </button>
                      </th>
                    </tr>
                  </tbody>
                </table>
              </div>
            ))}
          </div>
          <div className="row" style={{ marginTop: '35px' }}>
            <div className="col-3"></div>
            <div className="col-6" style={{ display: 'flex', justifyContent: 'center' }}>
              {/* <Paginate
                pageCount={result.totalPostsCount}
                pageRangeDisplayed={5}
                marginPagesDisplayed={0}
                previousLabel={'<<'}
                nextLabel={'>>'}
                onPageChange={handlePageClick}
                containerClassName={'pagination'}
                pageClassName={'pointer'}
                previousClassName={'pointer'}
                nextClassName={'pointer'}
                breakClassName={'dispalyNone pointer'}
              /> */}
            </div>
            <div className="col-3"></div>
          </div>
        </div>
      ) : (
        <div className="row" style={{ textAlign: 'center' }}>
          <h3>
            <br />
            <br />
            <br />
            <br />
            제안 받은 포지션이 없습니다.
          </h3>
        </div>
      )}
    </div>
  );
};

export default PositionProposalList;
